import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Terms of Service", description: "Terms governing use of StoreFlow." };
const lastUpdated = "July 23, 2026";
const supportEmail = "descriptionbuilderapp@gmail.com";
export default function TermsPage(){return <article className="mx-auto max-w-3xl px-6 py-20 lg:py-24"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-700">Legal</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">Terms of Service</h1><p className="mt-4 text-sm text-slate-500">Last updated: {lastUpdated}</p>
<section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-6"><p className="font-semibold text-slate-950">Legal review recommended</p><p className="mt-2 text-sm leading-6 text-slate-700">These Terms describe the intended commercial framework for StoreFlow and should be reviewed by qualified legal counsel before final commercial publication.</p></section>
<div className="mt-10 space-y-10 leading-8 text-slate-700">
<section><h2 className="text-2xl font-semibold text-slate-950">1. Agreement and intended use</h2><p className="mt-3">These Terms govern access to and use of StoreFlow. StoreFlow is designed primarily for small and growing Shopify wholesale merchants using documented and recommended Shopify Online Store environments.</p><p className="mt-3">By installing or using StoreFlow, you represent that you have authority to act for the merchant and agree to these Terms.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">2. Internal Beta</h2><p className="mt-3">StoreFlow is currently offered through controlled Internal Beta onboarding. Certain features, including Minimum Order, MOQ Rules, and checkout protection, may be included at no additional charge during Internal Beta.</p><p className="mt-3">Beta features may change, be limited, or be withdrawn as compatibility, capacity, security, and operational validation continues. Where reasonably practical, StoreFlow will provide notice of material changes.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">3. Recommended operating range</h2><p className="mt-3">Published catalog, cart, rule, product-selection, collection-selection, traffic, and compatibility figures are conservative onboarding guidance. They are not guaranteed maximum capacity, certified performance, or a service-level commitment.</p><p className="mt-3">Use outside documented guidance may require separate evaluation and may not be suitable for production reliance.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">4. Merchant testing and configuration responsibility</h2><p className="mt-3">You are responsible for accurately configuring rules, customer tags, selected products and collections, app embeds, checkout validation, themes, and related Shopify settings.</p><p className="mt-3">Before production reliance, you must test StoreFlow with your theme, catalog, cart, cart drawer, checkout, customer accounts, tags, installed apps, browsers, devices, discounts, and business workflows. Testing should be repeated after relevant changes.</p><p className="mt-3">You remain responsible for monitoring live orders and for the accuracy of your pricing, purchasing policies, customer communications, and contractual commitments.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">5. No universal enforcement guarantee</h2><p className="mt-3">StoreFlow is intended to assist with storefront restrictions and checkout validation. It does not guarantee that every non-compliant order, price display, purchase control, customer-access issue, or checkout attempt will be detected or prevented under every theme, browser, custom cart, custom checkout, third-party app, network condition, or Shopify configuration.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">6. Shopify and third-party dependencies</h2><p className="mt-3">StoreFlow depends on Shopify services, APIs, themes, app proxies, checkout capabilities, Shopify Functions, browsers, networks, payment systems, and third-party applications that StoreFlow does not control.</p><p className="mt-3">Changes, interruptions, limitations, incompatibilities, or failures in those systems may affect StoreFlow functionality.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">7. Capacity, performance, and availability</h2><p className="mt-3">Performance may vary based on catalog size and structure, traffic, theme complexity, rule count, installed apps, Shopify availability, network conditions, and concurrent usage.</p><p className="mt-3">StoreFlow does not currently provide guaranteed uptime, throughput, response time, concurrent capacity, error-free operation, or a formal SLA.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">8. Support scope</h2><p className="mt-3">Support is limited to documented StoreFlow workflows and environments within current Internal Beta guidance. Standard support does not include custom theme or checkout development, headless implementation, third-party code changes, enterprise architecture consulting, performance certification, continuous monitoring, or emergency operational response.</p><p className="mt-3"><Link href="/support" className="font-semibold text-emerald-700">Review the Support Policy</Link>.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">9. Fair use and service stability</h2><p className="mt-3">Where usage materially exceeds documented guidance or creates a reasonable risk to service stability, security, or integrity, StoreFlow may request reasonable information, recommend configuration changes, require separate evaluation, or apply proportionate temporary limitations where reasonably necessary.</p><p className="mt-3">Where practical, StoreFlow will provide notice and an opportunity to adjust usage. Immediate action may be taken where continued usage presents a material security, integrity, or service-stability risk.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">10. Independent records</h2><p className="mt-3">You should retain independent records of business-critical order policies, pricing policies, minimums, customer requirements, and StoreFlow configurations. StoreFlow should not be used as the sole record of contractual terms, pricing commitments, or operational requirements.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">11. Acceptable use</h2><p className="mt-3">You may not use StoreFlow to violate law, Shopify policies, another person&apos;s rights, or the security or integrity of any system. You may not bypass access controls, interfere with the service, introduce malicious code, or process information you are not authorized to use.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">12. Pricing, billing, and refunds</h2><p className="mt-3">Prices, billing intervals, trials, and material plan limitations will be presented before approval of a paid Shopify subscription. Shopify may process charges, taxes, credits, and billing adjustments under its own systems and terms.</p><p className="mt-3">Unless required by law or stated in a published refund policy, fees already charged are generally non-refundable. Verified duplicate charges, billing errors, or material service issues may be reviewed individually.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">13. Disclaimer of warranties</h2><p className="mt-3">To the maximum extent permitted by applicable law, StoreFlow is provided &quot;as is&quot; and &quot;as available.&quot; StoreFlow disclaims implied warranties to the extent they may lawfully be disclaimed.</p><p className="mt-3">Nothing in these Terms excludes warranties, remedies, or rights that applicable law does not permit to be excluded.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">14. Limitation of liability</h2><p className="mt-3">To the maximum extent permitted by applicable law, StoreFlow will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, lost revenue, lost sales, business interruption, loss of goodwill, loss of data, order errors, pricing errors, customer claims, or costs of substitute services.</p><p className="mt-3">Any aggregate liability cap, exclusions, and exceptions should be confirmed in a final legally reviewed version of these Terms. No provision limits liability where applicable law prohibits limitation.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">15. Suspension and termination</h2><p className="mt-3">You may uninstall StoreFlow at any time, subject to applicable Shopify billing terms. StoreFlow may suspend or terminate access where reasonably necessary to address security risks, nonpayment, unlawful activity, abuse, material violations, Shopify requirements, or threats to StoreFlow or other users.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">16. Privacy</h2><p className="mt-3">Information processing is described in the <Link href="/privacy" className="font-semibold text-emerald-700">Privacy Policy</Link>.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">17. Governing terms and changes</h2><p className="mt-3">Governing law, dispute resolution, indemnification, subscription renewal, notice procedures, and any binding liability cap require professional legal review before final publication.</p><p className="mt-3">StoreFlow may update these Terms to reflect product, legal, billing, security, or Shopify platform changes. Revised Terms will be posted with an updated date, and material changes will be communicated where reasonably practical.</p></section>
<section><h2 className="text-2xl font-semibold text-slate-950">18. Contact</h2><p className="mt-3">Questions may be sent to:</p><a href={`mailto:${supportEmail}?subject=StoreFlow%20Terms%20Question`} className="mt-3 inline-flex break-all font-semibold text-emerald-700">{supportEmail}</a></section>
</div></article>}
