import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Known Limitations", description: "Current StoreFlow implementation and validation boundaries." };
const sections = [
  ["Current implementation boundaries", ["Quick Order displays up to 100 variants per page.", "Collection membership checks are processed in batches of 50 product IDs.", "Automated collection membership testing currently covers 101 distinct products; real-store end-to-end validation for larger carts remains pending.", "Quick Order collection options have been fully validated up to 50 collections.", "Product title search currently reads up to 250 matching parent products.", "Availability filtering currently uses up to 25 GraphQL requests and approximately 2,500 underlying variants."]],
  ["Capacity validation status", ["Multi-merchant concurrency has not yet been fully benchmarked.", "Sustained high traffic and flash-sale traffic have not yet been fully benchmarked.", "SQLite sustained concurrent write behavior has not been certified for enterprise workloads.", "Large catalog, enterprise, guaranteed-capacity, and SLA-backed use cases require additional validation."]],
  ["Compatibility considerations", ["Theme and third-party app customizations may affect storefront behavior.", "Shopify platform changes, APIs, app proxies, checkout capabilities, browsers, networks, and third-party systems may affect functionality.", "Headless storefronts, fully custom carts, and heavily rewritten checkout experiences are not currently recommended for standard onboarding."]],
  ["Merchant verification responsibilities", ["Merchants should test Minimum Order, MOQ, Hide Prices, Quick Order, and checkout validation before production reliance.", "Testing should include guest and logged-in customers, customer tags, product and collection selections, cart pages, cart drawers, checkout, installed apps, browsers, and devices.", "Testing should be repeated after theme, app, checkout, catalog, or Shopify platform changes."]],
] as const;
export default function KnownLimitationsPage(){return <article className="mx-auto max-w-4xl px-6 py-20 lg:py-24"><Link href="/docs" className="text-sm font-semibold text-emerald-700">← Back to documentation</Link><h1 className="mt-8 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">Known limitations</h1><p className="mt-5 text-lg leading-8 text-slate-600">These notes describe current boundaries and validation status. They are not a defect list or a guarantee that configurations outside the guidance cannot work.</p><div className="mt-12 space-y-8">{sections.map(([title,items])=><section key={title} className="rounded-2xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-semibold text-slate-950">{title}</h2><ul className="mt-5 space-y-3 text-slate-700">{items.map(item=><li key={item} className="flex gap-3"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-amber-500" />{item}</li>)}</ul></section>)}</div></article>}
