import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Support", description: "StoreFlow Internal Beta support policy and contact information." };
const supportEmail = "descriptionbuilderapp@gmail.com";

const included = ["Installation and activation guidance", "Configuration of documented StoreFlow settings", "Assistance reproducing issues in recommended environments", "Review of whether a store appears to fall within current Internal Beta guidance", "Reasonable compatibility troubleshooting for Dawn and lightly customized Online Store 2.0 themes", "Guidance based on information supplied by the merchant"];
const excluded = ["Custom theme or checkout development", "Headless implementation", "Code changes to third-party apps", "Complex multi-app integration engineering", "Enterprise architecture consulting", "Performance or capacity certification", "Formal SLA, guaranteed response time, or guaranteed resolution time", "Continuous monitoring, emergency operational response, or business-continuity services"];

export default function SupportPage(){return <div className="mx-auto max-w-6xl px-6 py-20 lg:py-24"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-700">Support</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">Support for documented StoreFlow workflows</h1><p className="mt-5 text-lg leading-8 text-slate-600">Support is provided for documented StoreFlow features and environments within current Internal Beta guidance.</p></div>
<div className="mt-14 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-8"><h2 className="text-2xl font-semibold text-slate-950">Standard support includes</h2><ul className="mt-5 space-y-3 text-slate-700">{included.map(x=><li key={x}>• {x}</li>)}</ul></section><section className="rounded-2xl border border-slate-200 bg-white p-8"><h2 className="text-2xl font-semibold text-slate-950">Standard support does not include</h2><ul className="mt-5 space-y-3 text-slate-700">{excluded.map(x=><li key={x}>• {x}</li>)}</ul></section></div>
<section className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-8"><h2 className="text-2xl font-semibold text-slate-950">Compatibility troubleshooting</h2><p className="mt-4 leading-8 text-slate-700">Support may ask the merchant to reproduce an issue on Dawn or another minimally customized Online Store 2.0 theme before further investigation. Compatibility guidance is based on the environment and information available at the time of review and is not a guarantee against future theme, app, Shopify, or configuration changes.</p><p className="mt-3 leading-8 text-slate-700">Large catalogs, high concurrency, custom themes, headless storefronts, enterprise requirements, and complex third-party integrations may require separate evaluation.</p></section>
<div className="mt-6 grid gap-6 md:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><h2 className="text-2xl font-semibold text-slate-950">Documentation</h2><p className="mt-3 leading-7 text-slate-600">Review setup, supported-use, compatibility, and limitation guidance before contacting support.</p><Link href="/docs" className="mt-6 inline-flex font-semibold text-emerald-700">View documentation →</Link></section><section className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><h2 className="text-2xl font-semibold text-slate-950">Contact support</h2><p className="mt-3 leading-7 text-slate-600">Include your store URL, theme, affected feature, steps to reproduce, expected behavior, and screenshots or errors.</p><a href={`mailto:${supportEmail}?subject=StoreFlow%20Support%20Request`} className="mt-6 inline-flex break-all font-semibold text-emerald-700">{supportEmail} →</a></section></div></div>}
